query User {
  Viewer {
    id
    name
    mediaListOptions {
      scoreFormat
      animeList {
        customLists
      }
      mangaList {
        customLists
      }
    }
    options {
      profileColor
    }
    avatar {
      medium
    }
  }
}